DROP TABLE IF EXISTS job_offers;

CREATE TABLE job_offers(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(200) NOT NULL,
body VARCHAR(1500) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);